unpackaged/main/default/objects/Help_Article__c/Help_Article__c.object-meta.xml
<CustomObject>
    <label>Help Article</label>
    <nameField>
        <label>Help Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Help_Article__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Help_Article__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/classes/SearchInVFController.cls
public class SearchInVFController{

    public list <Help_Article__c> defaultArticles {get;set;}
    public list <Help_Article__c> searchArticles {get;set;}
    
    public String searchKey {get;set;}
    
    public String currentRecordId {get;set;}    
    public String topicName {get;set;}    
    
    public SearchInVFController( ) {   
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');   

        switch on currentRecordId.substring(0,3) {
            when '001' { topicName = 'Account'; }
            when '003' { topicName = 'Contact'; }
            when '00Q' { topicName = 'Lead'; }
            when '006' { topicName = 'Opportunity'; }
            when 'a19' { topicName = 'Quote'; }
            when else { topicName = 'General'; }
        }

   
        string searchquery='select Name, URL__c, Topic__c from help_article__c where Topic__c includes (\''+ topicName +'\') Limit 10';
        defaultArticles = Database.query(searchquery);
    }
    
    public void search(){
        string searchquery='select Name, URL__C, Topic__c from help_article__c where name like \'%'+searchKey+'%\' OR Topic__c includes (\''+searchKey+'\') Limit 5';
        searchArticles = Database.query(searchquery);
    }
    
    public void clear(){
        searchArticles .clear();
        searchKey = '';
    }
}