unpackaged/main/default/objects/Help_Article__c/Help_Article__c.object-meta.xml
<CustomObject>
    <label>Help Article</label>
    <nameField>
        <label>Help Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Help_Article__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Help_Article__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Business_Line__c.field-meta.xml
<CustomField>
    <fullName>Business_Line__c</fullName>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Postal_Code__c</fullName>
    <description>Postal/Zip Code of the site where the potential job will take place</description>
    <inlineHelpText>Postal/Zip Code of the site where the potential job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site Postal/Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/globalValueSets/Business_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanguard</fullName>
    </customValue>
    <customValue>
        <fullName>LodgeLinks</fullName>
    </customValue>
    <customValue>
        <fullName>BDGL</fullName>
    </customValue>
    <customValue>
        <fullName>MSS</fullName>
    </customValue>
    <customValue>
        <fullName>WFS</fullName>
    </customValue>
    <customValue>
        <fullName>ES CA</fullName>
    </customValue>
    <customValue>
        <fullName>ES US</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Single Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Multi-unit Complexes</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Used Fleet</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Custom Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Modular Classrooms</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Additional Services</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Traditional Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Rapid Deployment Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Plug &amp; Stay Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Build. Own. Operate. Village</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Not sure</fullName>
    </customValue>
    <customValue>
        <fullName>WFS_US</fullName>
    </customValue>
    <customValue>
        <fullName>WFS_CA</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX</fullName>
        <isActive>false</isActive>
        <label>BOXX</label>
    </customValue>
    <customValue>
        <fullName>Please Select</fullName>
        <isActive>false</isActive>
        <label>Please Select</label>
    </customValue>
    <customValue>
        <fullName>Vanguard;Vanguard</fullName>
        <isActive>false</isActive>
        <label>Vanguard;Vanguard</label>
    </customValue>
    <description>Business Lines to be used for Sales Regions and Lead Mapping</description>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SearchInVFControllerTest.cls
@isTest
public class SearchInVFControllerTest {
   @isTest static void SearchInVFControllerTest(){
        Lead l = new Lead();
        l.Business_Line__c = 'AUS - Additional Services';
        l.FirstName = 'test';
        l.LastName = 'test';
        l.Opportunity_Postal_Code__c = '00000';
        insert l;
       
        help_article__c ha = new help_article__c();
        ha.Name = 'Test';
        ha.URL__c = 'google.com';
        ha.Topic__c = 'Lead';
        insert ha;
       
       Test.StartTest();
       apexpages.currentpage().getparameters().put('Id',string.valueOf(l.Id)) ;
       SearchInVFController sv = new SearchInVFController();
       sv.search();
       sv.clear();
       Test.Stoptest();
    }
    

}