unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accounting Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Accounting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used in handover.</description>
    <inlineHelpText>Customer contact for accounting issues.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Looking for active contacts associated with this opportunity's account.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Accounting Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_App_Obtained__c.field-meta.xml
<CustomField>
    <fullName>Credit_App_Obtained__c</fullName>
    <description>Used for handover.</description>
    <inlineHelpText>Has customer provided complete Credit Limit Application?</inlineHelpText>
    <label>Credit App Obtained?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason__c</fullName>
    <description>Details to clarify Loss Reason</description>
    <inlineHelpText>Details to clarify Loss Reason</inlineHelpText>
    <label>Reason Details</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer contact we primarily work with regarding this Opportunity.</inlineHelpText>
    <label>Purchasing Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Looking for active contacts associated with this opportunity's account.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project_Location_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Location_Address__c</fullName>
    <description>Street address of the site where the job will take place</description>
    <inlineHelpText>Street address of the site where the job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project_Location_City__c.field-meta.xml
<CustomField>
    <fullName>Project_Location_City__c</fullName>
    <description>City of the site where the job will take place</description>
    <inlineHelpText>City of the site where the job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>Project_Location_Country__c</fullName>
    <description>Country of the site where the job will take place</description>
    <inlineHelpText>Country of the site where the job will take place. Auto-filled from Project Source, when selected. Auto-filled from Branch when Opportunity is created.</inlineHelpText>
    <label>Site Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project_Location_Province__c.field-meta.xml
<CustomField>
    <fullName>Project_Location_Province__c</fullName>
    <description>Province/State of the site where the job will take place</description>
    <inlineHelpText>Province/State of the site where the job will take place. Auto-filled from Project Source, when selected. Auto-filled from Branch when Opportunity is created.</inlineHelpText>
    <label>Site Province/State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Location_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Bowen Basin</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Central Coast/Hunter</fullName>
            </value>
            <value>
                <fullName>Central West</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Galillee Basin</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Goldfields</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Reason_s_Won_Lost_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Reason_s_Won_Lost_Cancelled__c</fullName>
    <label>Reason(s) Won/Lost /Cancelled</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project Cancelled</fullName>
            </value>
            <value>
                <fullName>Client Not Awarded</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Supply Logistics</fullName>
            </value>
            <value>
                <fullName>Fleet Availability</fullName>
            </value>
            <value>
                <fullName>Non-fleet Availability</fullName>
            </value>
            <value>
                <fullName>Competitor Relationship</fullName>
            </value>
            <value>
                <fullName>Client Unresponsive</fullName>
            </value>
            <value>
                <fullName>Site Logistics</fullName>
            </value>
            <value>
                <fullName>Projects on Hold</fullName>
            </value>
            <value>
                <fullName>Client Relationship</fullName>
            </value>
            <value>
                <fullName>Follow up/ Clean Up</fullName>
            </value>
            <value>
                <fullName>Withdraw: Excessive Submittals Required</fullName>
            </value>
            <value>
                <fullName>Withdraw: Price Hold Too Long</fullName>
            </value>
            <value>
                <fullName>Withdraw: Risk Exposure</fullName>
            </value>
            <value>
                <fullName>Withdraw: Too Many Resources Needed</fullName>
            </value>
            <value>
                <fullName>Withdraw: Timeline</fullName>
            </value>
            <value>
                <fullName>Withdraw: Contract Terms</fullName>
            </value>
            <value>
                <fullName>Withdraw: Liquidated Damages Unacceptable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer contact who will handle site logistics for this job.</description>
    <inlineHelpText>Customer contact who will handle site logistics for this job.</inlineHelpText>
    <label>Site Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Site Contact)</relationshipLabel>
    <relationshipName>OpportunitiesSiteContact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestSubmitApprovalWithEvaluation.cls
@isTest
public class TestSubmitApprovalWithEvaluation {
    static testMethod void SubmitApprovalWithEvaluationTest() {

// Create a test account
     Account testAcct = new Account (Name = 'My Test Account');
     insert testAcct;

    // Create a related contact
         Contact testContact = new Contact (FirstName = 'Fred',
         LastName = 'Jones',
         Phone = '4035551212',
         MobilePhone = '4035551234',
         Email = 'Fred@example.com');
         insert testContact;
    // Creates first opportunity
    Opportunity oppt = new Opportunity(Name ='New mAWS Deal',
                            AccountID = testAcct.ID,
                            StageName = 'Won',
                            Amount = 3000,
                            Credit_App_Obtained__c = 'Yes',
                            Reason_s_Won_Lost_Cancelled__c = 'Availability',
                            Other_Reason__c = 'Because Scott Said So',
                            Primary_Contact__c = testContact.ID,
                            Site_Contact__c = testContact.ID,
                            Accounting_Contact__c = testContact.ID,
                            Project_Location_Address__c = '101 9 Ave SW',
                            Project_Location_City__c = 'Calgary',
                            Project_Location_Country__c = 'Canada',
                            Project_Location_Province__c = 'Alberta',
                            CloseDate = System.today());

   insert oppt;

        Test.startTest();
            {

    // Create a test opportunity
    Opportunity mAWSUsage = new Opportunity( Name = 'mAWS Usage',
                              AccountId = testAcct.Id,
                              StageName = 'Negotiations',
                              CloseDate = System.today(),
                              Type = 'New Business - Add',
                              Amount = 555888555);

  insert  mAWSUsage;


    // Get the opportunity, verify the stage name and close date
  mAWSUsage = [SELECT StageName, CloseDate, Name, Type, Amount, Reason_s_Won_Lost_Cancelled__c
             FROM Opportunity 
             WHERE id = :mAWSUsage.Id];
             
             ApexPages.CurrentPage().getparameters().put('pid', mAWSUsage.Id);
             ApexPages.StandardController sc = new ApexPages.standardController(mAWSUsage);
                     
             // test pass case   
             SubmitApprovalWithEvaluationController sawe= new SubmitApprovalWithEvaluationController(sc);
             mAWSUsage.Reason_s_Won_Lost_Cancelled__c = 'Cancelled';
             sawe.opp = mAWSUsage;
             sawe.approve();
             system.assert(true);
                
             SubmitApprovalWithEvaluationController sawe1= new SubmitApprovalWithEvaluationController(sc);
             sawe1.opp = mAWSUsage;
             sawe1.approve();
             system.assert(true);
                
             // Test fail case   
             SubmitApprovalWithEvaluationController sawe2= new SubmitApprovalWithEvaluationController(sc);
             mAWSUsage.Reason_s_Won_Lost_Cancelled__c = '';
             sawe2.opp = mAWSUsage;
             sawe2.approve();


               // Test resubmit fail - I don't think that it resummits the same one like I want.
             ApexPages.CurrentPage().getparameters().put('pid', mAWSUsage.Id);
             ApexPages.StandardController sc3 = new ApexPages.standardController(mAWSUsage);
             SubmitApprovalWithEvaluationController sawe3= new SubmitApprovalWithEvaluationController(sc3);
             sawe3.approve();
             system.assert(true);
                
             system.assert(true);
            }
            Test.stopTest(); 
             
   }

}