unpackaged/main/default/objects/Lead/fields/AD_Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>AD_Distribution_Group__c</fullName>
    <label>AD Distribution Group</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Business_Line__c.field-meta.xml
<CustomField>
    <fullName>Business_Line__c</fullName>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lead_Source_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Detail__c</fullName>
    <inlineHelpText>Details about the origin of this Lead. At conversion, mapped to Contact, Account and Opportunity.</inlineHelpText>
    <label>Lead Source Detail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_City__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_City__c</fullName>
    <description>City of the site where the potential job will take place</description>
    <inlineHelpText>City of the site where the potential job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Country__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Country__c</fullName>
    <description>Country of the site where the potential job will take place</description>
    <inlineHelpText>Country of the site where the potential job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Postal_Code__c</fullName>
    <description>Postal/Zip Code of the site where the potential job will take place</description>
    <inlineHelpText>Postal/Zip Code of the site where the potential job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site Postal/Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Street__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Street__c</fullName>
    <label>Site Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Code__c</fullName>
    <label>Sales Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Website_Source__c.field-meta.xml
<CustomField>
    <fullName>Website_Source__c</fullName>
    <description>Used to map which website a Lead is sourced from when creating Leads via Web-To-Lead</description>
    <inlineHelpText>Website that was used by customer to create Lead</inlineHelpText>
    <label>Website Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Website_Source</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/objects/Lead/recordTypes/Vanguard.recordType-meta.xml
<RecordType>
    <fullName>Vanguard</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Vanguard</label>
</RecordType>

unpackaged/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Region__c/fields/AD_Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>AD_Distribution_Group__c</fullName>
    <description>Azure Active Directory Distribution Group for users that want to be notified in addition to the Lead Owner and Inside Sales Rep</description>
    <inlineHelpText>Azure Active Directory Distribution Group for users that want to be notified in addition to the Lead Owner and Inside Sales Rep</inlineHelpText>
    <label>AD Distribution Group</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Sales_Region__c/fields/Business_Line__c.field-meta.xml
<CustomField>
    <fullName>Business_Line__c</fullName>
    <description>Identifies the area of the Product, Industry, Business, etc. for this Sales Region</description>
    <inlineHelpText>Identifies the area of the Product, Industry, Business, etc. for this Sales Region</inlineHelpText>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sales_Region__c/fields/Inside_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sales_Region_Code__c/Sales_Region_Code__c.object-meta.xml
<CustomObject>
    <label>Sales Region Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Region Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Region_Code_Junction__c/Sales_Region_Code_Junction__c.object-meta.xml
<CustomObject>
    <label>Sales Region - Code Junction</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Region - Code Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Region - Code Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Region_Code_Junction__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipName>Sales_Region_Zip_Code_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sales_Region_Code_Junction__c/fields/Sales_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Code__c</fullName>
    <inlineHelpText>This can be a Zip/Postal Code or even the name of a City</inlineHelpText>
    <label>Sales Region Code</label>
    <referenceTo>Sales_Region_Code__c</referenceTo>
    <relationshipLabel>Sales Region - Code Junction</relationshipLabel>
    <relationshipName>Sales_Region_Zip_Code_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Business_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanguard</fullName>
    </customValue>
    <customValue>
        <fullName>LodgeLinks</fullName>
    </customValue>
    <customValue>
        <fullName>BDGL</fullName>
    </customValue>
    <customValue>
        <fullName>MSS</fullName>
    </customValue>
    <customValue>
        <fullName>WFS</fullName>
    </customValue>
    <customValue>
        <fullName>ES CA</fullName>
    </customValue>
    <customValue>
        <fullName>ES US</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Single Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Multi-unit Complexes</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Used Fleet</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Custom Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Modular Classrooms</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Additional Services</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Traditional Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Rapid Deployment Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Plug &amp; Stay Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Build. Own. Operate. Village</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Not sure</fullName>
    </customValue>
    <customValue>
        <fullName>WFS_US</fullName>
    </customValue>
    <customValue>
        <fullName>WFS_CA</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX</fullName>
        <isActive>false</isActive>
        <label>BOXX</label>
    </customValue>
    <customValue>
        <fullName>Please Select</fullName>
        <isActive>false</isActive>
        <label>Please Select</label>
    </customValue>
    <customValue>
        <fullName>Vanguard;Vanguard</fullName>
        <isActive>false</isActive>
        <label>Vanguard;Vanguard</label>
    </customValue>
    <description>Business Lines to be used for Sales Regions and Lead Mapping</description>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Website_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUS Website</fullName>
    </customValue>
    <customValue>
        <fullName>BOXXCA Website</fullName>
    </customValue>
    <customValue>
        <fullName>BOXXUS Website</fullName>
    </customValue>
    <customValue>
        <fullName>Britco Website</fullName>
    </customValue>
    <customValue>
        <fullName>Camps Website</fullName>
    </customValue>
    <customValue>
        <fullName>ESCA Website</fullName>
    </customValue>
    <customValue>
        <fullName>ESUS Website</fullName>
    </customValue>
    <customValue>
        <fullName>MPA Website</fullName>
    </customValue>
    <customValue>
        <fullName>WFS Camps</fullName>
    </customValue>
    <customValue>
        <fullName>Vanguard</fullName>
    </customValue>
    <description>Website used by customer</description>
    <masterLabel>Website Source</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LeadTriggerHandlerTest.cls
@isTest(seealldata=false)
public class LeadTriggerHandlerTest {
    @isTest static void LeadTriggerHandlerMethod(){
        Sales_Region_Code_Junction__c srj = new Sales_Region_Code_Junction__c();
        //srj.Sales_Region__c = 'a2F7d000000i1RoEAI';
        srj.Sales_Region__c = 'a2F4u000002xhF9EAI';
        //srj.Sales_Region_Code__c = 'a2H7d000001uBRWEA2';
        srj.Sales_Region_Code__c = 'a2E4u000002mMa0EAE';
        insert srj;
        
        Sales_Region__c sr = new Sales_Region__c();
        sr.Name = 'Name';
        //sr.Inside_Sales_Rep__c = '0054u0000071Snu';
        sr.Inside_Sales_Rep__c = '0050g00000674gdAAA';
        sr.AD_Distribution_Group__c = 'test@test.com';
        insert sr;
        
        
        Lead l = new Lead();
        l.Business_Line__c = 'MSS';
        l.FirstName = 'test';
        l.LastName = 'test';
        l.Opportunity_City__c = 'XYZ';
        l.Opportunity_Street__c = 'XYZ Street';
        l.Opportunity_Postal_Code__c = 'T0J123';
        l.PostalCode = 'T0J123';
        l.CountryCode = 'CA';
        //l.RecordTypeId = '0127d0000005jdJAAQ';
        l.RecordTypeId = '0124u000000gtAYAAY';
        l.LeadSource = '360MobileOffice';
        //l.Website_Source__c = 'Vanguard';
        //l.Sales_Region_Code__c = '01865';
        l.Opportunity_Country__c = 'CA';
        insert l;
        
        Lead l2 = new Lead();
        l2.Business_Line__c = 'MSS';
        l2.FirstName = 'test1';
        l2.LastName = 'test1';
        l2.Opportunity_City__c = 'XYZ';
        l2.Opportunity_Street__c = 'XYZ Street';
        l2.Opportunity_Postal_Code__c = '01865';
        l2.PostalCode = '01865';
        l2.CountryCode = 'US';
        //l2.RecordTypeId = '0127d0000005jdJAAQ';
        l2.RecordTypeId = '0124u000000gtAYAAY';
        l2.LeadSource = '360MobileOffice';
        //l2.Website_Source__c = 'Vanguard';
        //l.Sales_Region_Code__c = '01865';
        l2.Opportunity_Country__c = 'US';
        insert l2;

		Lead l3 = new Lead();
        l3.FirstName = 'test3';
        l3.LastName = 'test3';
        l3.Opportunity_City__c = 'XYZ';
        l3.Opportunity_Street__c = 'XYZ Street';
        l3.Opportunity_Postal_Code__c = '01865';
        l3.PostalCode = '01865';
        l3.CountryCode = 'US';
        l3.leadsource = 'Website';
        l3.Website_Source__c = 'BOXXUS Website';
        l3.Lead_Source_Detail__c = 'Live Chat';
        //l2.RecordTypeId = '0127d0000005jdJAAQ';
        //l3.RecordTypeId = '0124u000000gtAYAAY';
        //l.Sales_Region_Code__c = '01865';
        l3.Opportunity_Country__c = 'US';
        insert l3;
    }

}