unpackaged/main/default/objects/Lead/fields/AD_Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>AD_Distribution_Group__c</fullName>
    <label>AD Distribution Group</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <label>Brand Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Business_Line__c.field-meta.xml
<CustomField>
    <fullName>Business_Line__c</fullName>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Delivery_ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>Delivery_ZIP_Code__c</fullName>
    <description>ZIP Code where the Building is to be Delivered. Used primarily for 360 mobile office web leads.</description>
    <label>Delivery ZIP Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Email_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Opt-In</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Inside_Sales_Rep_Email__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Rep_Email__c</fullName>
    <label>Inside Sales Rep Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lead_Source_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Detail__c</fullName>
    <inlineHelpText>Details about the origin of this Lead. At conversion, mapped to Contact, Account and Opportunity.</inlineHelpText>
    <label>Lead Source Detail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_City__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_City__c</fullName>
    <description>City of the site where the potential job will take place</description>
    <inlineHelpText>City of the site where the potential job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Country__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Country__c</fullName>
    <description>Country of the site where the potential job will take place</description>
    <inlineHelpText>Country of the site where the potential job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Postal_Code__c</fullName>
    <description>Postal/Zip Code of the site where the potential job will take place</description>
    <inlineHelpText>Postal/Zip Code of the site where the potential job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site Postal/Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Province_State_Territory__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Province_State_Territory__c</fullName>
    <description>Province/State of the site where the potential job will take place</description>
    <inlineHelpText>Province/State of the site where the job will take place. Auto-filled from Project Source, when selected.</inlineHelpText>
    <label>Site Province/State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Opportunity_Street__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Street__c</fullName>
    <label>Site Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>OLD - Postal/Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>OLD - Province/State/Territory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Bowen Basin</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Central Coast/Hunter</fullName>
            </value>
            <value>
                <fullName>Central West</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Galillee Basin</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Goldfields</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Code__c</fullName>
    <label>Sales Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Region_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Region(Look-up)</label>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Vanguard_State__c.field-meta.xml
<CustomField>
    <fullName>Vanguard_State__c</fullName>
    <formula>TEXT(StateCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vanguard State</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Website_Source__c.field-meta.xml
<CustomField>
    <fullName>Website_Source__c</fullName>
    <description>Used to map which website a Lead is sourced from when creating Leads via Web-To-Lead</description>
    <inlineHelpText>Website that was used by customer to create Lead</inlineHelpText>
    <label>Website Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Website_Source</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/objects/Lead/recordTypes/Vanguard.recordType-meta.xml
<RecordType>
    <fullName>Vanguard</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Vanguard</label>
</RecordType>

unpackaged/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Region__c/fields/AD_Distribution_Group__c.field-meta.xml
<CustomField>
    <fullName>AD_Distribution_Group__c</fullName>
    <description>Azure Active Directory Distribution Group for users that want to be notified in addition to the Lead Owner and Inside Sales Rep</description>
    <inlineHelpText>Azure Active Directory Distribution Group for users that want to be notified in addition to the Lead Owner and Inside Sales Rep</inlineHelpText>
    <label>AD Distribution Group</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Sales_Region__c/fields/Business_Line__c.field-meta.xml
<CustomField>
    <fullName>Business_Line__c</fullName>
    <description>Identifies the area of the Product, Industry, Business, etc. for this Sales Region</description>
    <inlineHelpText>Identifies the area of the Product, Industry, Business, etc. for this Sales Region</inlineHelpText>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sales_Region__c/fields/Inside_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sales_Region_Code__c/Sales_Region_Code__c.object-meta.xml
<CustomObject>
    <label>Sales Region Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Region Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Region_Code_Junction__c/Sales_Region_Code_Junction__c.object-meta.xml
<CustomObject>
    <label>Sales Region - Code Junction</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Region - Code Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Region - Code Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Region_Code_Junction__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipName>Sales_Region_Zip_Code_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sales_Region_Code_Junction__c/fields/Sales_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Code__c</fullName>
    <inlineHelpText>This can be a Zip/Postal Code or even the name of a City</inlineHelpText>
    <label>Sales Region Code</label>
    <referenceTo>Sales_Region_Code__c</referenceTo>
    <relationshipLabel>Sales Region - Code Junction</relationshipLabel>
    <relationshipName>Sales_Region_Zip_Code_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Business_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanguard</fullName>
    </customValue>
    <customValue>
        <fullName>LodgeLinks</fullName>
    </customValue>
    <customValue>
        <fullName>BDGL</fullName>
    </customValue>
    <customValue>
        <fullName>MSS</fullName>
    </customValue>
    <customValue>
        <fullName>WFS</fullName>
    </customValue>
    <customValue>
        <fullName>ES CA</fullName>
    </customValue>
    <customValue>
        <fullName>ES US</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Single Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Multi-unit Complexes</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Used Fleet</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Custom Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Modular Classrooms</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Additional Services</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Traditional Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Rapid Deployment Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Plug &amp; Stay Camps</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Build. Own. Operate. Village</fullName>
    </customValue>
    <customValue>
        <fullName>AUS - Not sure</fullName>
    </customValue>
    <customValue>
        <fullName>WFS_US</fullName>
    </customValue>
    <customValue>
        <fullName>WFS_CA</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX</fullName>
        <isActive>false</isActive>
        <label>BOXX</label>
    </customValue>
    <customValue>
        <fullName>Please Select</fullName>
        <isActive>false</isActive>
        <label>Please Select</label>
    </customValue>
    <customValue>
        <fullName>Vanguard;Vanguard</fullName>
        <isActive>false</isActive>
        <label>Vanguard;Vanguard</label>
    </customValue>
    <description>Business Lines to be used for Sales Regions and Lead Mapping</description>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Website_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUS Website</fullName>
    </customValue>
    <customValue>
        <fullName>BOXXCA Website</fullName>
    </customValue>
    <customValue>
        <fullName>BOXXUS Website</fullName>
    </customValue>
    <customValue>
        <fullName>Britco Website</fullName>
    </customValue>
    <customValue>
        <fullName>Camps Website</fullName>
    </customValue>
    <customValue>
        <fullName>ESCA Website</fullName>
    </customValue>
    <customValue>
        <fullName>ESUS Website</fullName>
    </customValue>
    <customValue>
        <fullName>MPA Website</fullName>
    </customValue>
    <customValue>
        <fullName>WFS Camps</fullName>
    </customValue>
    <customValue>
        <fullName>Vanguard</fullName>
    </customValue>
    <description>Website used by customer</description>
    <masterLabel>Website Source</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler {
    public static void leadHandler(list<lead> Newlead){
        try{
            
            
            set<string> zipCode = new set<string>();
        	set<string> businessLine = new set<string>();
       	 	Map<string,Sales_Region_Code_Junction__c> newMaplead = new map<string,Sales_Region_Code_Junction__c>();
        	for(Lead lead:Newlead){	
                System.debug('DEBUG INFORMATION:');
                System.debug('Lead ID: '+lead.Id);
                System.debug('Lead Country: '+Lead.Country);
                System.debug('Lead Country Code: '+Lead.CountryCode);
                System.debug('Lead State: '+Lead.State);
                System.debug('Lead State Code: '+Lead.StateCode);
                System.debug('Zip Code'+Lead.PostalCode+'/ '+Lead.Postal_Code__c);
                System.debug('Lead Record Type ID: '+Lead.RecordTypeId);
                System.debug('Lead Brand Code: '+Lead.Brand_Code__c);
                System.debug('Lead Business Line: '+Lead.Business_Line__c);
                System.debug('Lead Sales Region Code: '+Lead.Sales_Region_Code__c);
                System.debug('Lead Site/Postal Code: '+Lead.Opportunity_Postal_Code__c);
                System.debug('Lead  Site Country: '+Lead.Opportunity_Country__c);
                System.debug('Email Opt in: '+Lead.Email_Opt_In__c);
                System.debug('Email Opt Out: '+Lead.HasOptedOutOfEmail);
                System.debug('Site Province/State: '+Lead.Opportunity_Province_State_Territory__c);

                System.debug('Lead Business Line: '+Lead.Business_Line__c);
                if((lead.PostalCode == ''||lead.PostalCode	== null) && (lead.Opportunity_Postal_Code__c != null || lead.Opportunity_Postal_Code__c != '')){
                    lead.PostalCode = lead.Opportunity_Postal_Code__c;
                }
                
  				/*if((lead.Vanguard_State__c == ''||lead.Vanguard_State__c	== null) && (lead.Opportunity_Province_State_Territory__c != null || lead.Opportunity_Province_State_Territory__c != '')){
                    lead.Vanguard_State__c = lead.Opportunity_Province_State_Territory__c;
                }*/
                
                /*if((Lead.State == ''||Lead.State == null) && (lead.Opportunity_Province_State_Territory__c != null || lead.Opportunity_Province_State_Territory__c != '')){
                    lead.State = lead.Opportunity_Province_State_Territory__c;
                }*/
                
                if((lead.City == ''||lead.City	== null) && (lead.Opportunity_City__c != null || lead.Opportunity_City__c != '')){
                    lead.City = lead.Opportunity_City__c;
                }

                
                if((lead.Street == ''||lead.Street	== null) && (lead.Opportunity_Street__c != null || lead.Opportunity_Street__c != '')){
                    lead.Street = lead.Opportunity_Street__c;
                }
                
                if((lead.Delivery_ZIP_Code__c == ''||lead.Delivery_ZIP_Code__c	== null) && (lead.Opportunity_Postal_Code__c != null || lead.Opportunity_Postal_Code__c != '') &&(lead.Website_Source__c == 'Vanguard')){
                    lead.Delivery_ZIP_Code__c = lead.Opportunity_Postal_Code__c;
                
                }//if the website source is vanguard, populating the delivery zip code field and the Vanguard state field
                
                if(lead.RecordTypeID == '0124u000000gtAYAAY'){
                    lead.Brand_Code__c = 'Vanguard';
                    lead.Business_Line__c = 'Vanguard';
                    lead.Sales_Region_Code__c = lead.PostalCode;
                    lead.Delivery_ZIP_Code__c = lead.PostalCode;
                    lead.CountryCode = 'US';
                    lead.CurrencyIsoCode = 'USD';
                    system.debug(Lead.Opportunity_Country__c);
                    system.debug( lead.CountryCode);
                                
                }
             
                
                if(lead.leadSource == '360MobileOffice'){
                     lead.Sales_Region_Code__c = lead.PostalCode;
                     lead.Opportunity_Postal_Code__c = lead.PostalCode;
                     lead.Delivery_ZIP_Code__c = lead.PostalCode;
                     lead.Opportunity_Province_State_Territory__c = lead.StateCode;
                     lead.Opportunity_City__c = lead.City;
                     lead.CountryCode = 'US';
                }
                
                 if(lead.Website_Source__c == 'BOXXUS Website' && lead.Lead_Source_Detail__c == 'Live Chat'){
                     lead.Sales_Region_Code__c = lead.Opportunity_Postal_Code__c;
                     //lead.Opportunity_Postal_Code__c = lead.PostalCode;
                     lead.Delivery_ZIP_Code__c = lead.PostalCode;
                     lead.Business_Line__c = 'MSS';
                     //lead.Opportunity_Province_State_Territory__c = lead.StateCode;
                     //lead.Opportunity_City__c = lead.City;
                     lead.Brand_Name__c = 'a2B4u000006XprQEAS';
                     lead.CountryCode = 'US';
                }
                
                if((lead.Opportunity_Country__c == '' || lead.Opportunity_Country__c == null)&&(lead.CountryCode != ''||lead.CountryCode != null)){
                    lead.Opportunity_Country__c = lead.CountryCode;
                }
                
				system.debug('Enter For'+lead.Sales_Region_Code__c+', '+lead.Business_Line__c+', '+lead.Opportunity_Country__c+' '+lead.RecordTypeId);            
            	if(lead.Sales_Region_Code__c != null && lead.Sales_Region_Code__c != ''
               		&& lead.Business_Line__c != null &&  lead.Business_Line__c != '' && (lead.Opportunity_Country__c.toUpperCase() == 'CA'||lead.Opportunity_Country__c.toUpperCase() == 'Canada')
                    &&(lead.Business_Line__c !='WFS_CA')&&(lead.Business_Line__c !='WFS_US')&&(lead.Business_Line__c !='ES CA')){
                  	 zipCode.add(lead.Sales_Region_Code__c.substring(0,3).toUpperCase());
                   	businessLine.add(lead.Business_Line__c);
                   	system.debug('Zip Code is: '+zipCode);
             	}
                else
                    if(lead.Sales_Region_Code__c != null && lead.Sales_Region_Code__c != ''
               		&& lead.Business_Line__c != null &&  lead.Business_Line__c != '' && (lead.Opportunity_Country__c.toUpperCase() == 'US'||lead.Opportunity_Country__c.toUpperCase() == 'United States'||lead.Opportunity_Country__c.toUpperCase() == 'USA')
                       ){
                  	 zipCode.add(lead.Sales_Region_Code__c.substring(0,5).toUpperCase());
                   	businessLine.add(lead.Business_Line__c);
                   	system.debug('Zip Code is: '+zipCode);
             	}
            	else
                	if(lead.Sales_Region_Code__c != null && lead.Sales_Region_Code__c != ''
             			  && lead.Business_Line__c != null &&  lead.Business_Line__c != ''){
                  		 zipCode.add(lead.Sales_Region_Code__c);
                   		 businessLine.add(lead.Business_Line__c);
                  		 system.debug('Zip Code is: '+zipCode);
           		 }
                /*else
                  if(lead.leadSource == '360MobileOffice'){
              		  lead.Sales_Region_Code__c = lead.PostalCode;
                      lead.Delivery_ZIP_Code__c = lead.PostalCode;
                      zipCode.add(lead.Delivery_ZIP_Code__c);
                      businessLine.add(lead.Business_Line__c);
                      system.debug('Zip Code is: '+zipCode);
              }*/
           
			System.debug	(lead.CountryCode);
            System.debug    (lead.Province__c); 
            system.debug	(lead.Sales_Region_ID__c);
            System.debug	(lead.Business_Line__c);
        }
        for(Sales_Region_Code_Junction__c SRJUn:[select id,Sales_Region__r.Business_Line__c,Sales_Region__r.Name,Sales_Region_Code__r.Name,Sales_Region__r.Inside_Sales_Rep__r.Email,Sales_Region__r.Inside_Sales_Rep__r.Name,Sales_Region__r.AD_Distribution_Group__c from Sales_Region_Code_Junction__c
                                                     where  Sales_Region_Code__r.Name IN: zipCode and Sales_Region__r.Business_Line__c IN:businessLine  ]){
                                                         /* if(newMaplead.containsKey(SRJUn.Zip_Postal_Code__r.Name +SRJUn.Business_Line__c)){
lead ld = newMaplead.get(SRJUn.Zip_Postal_Code__r.Name +SRJUn.Business_Line__c);
ld.Sales_Region__c = SRJUn.Sales_Region__r.Name;
}*/
                                                       system.debug(SRJUn.Sales_Region_Code__r.Name+SRJUn.Sales_Region__r.Business_Line__c );
                                                         newMaplead.put(SRJUn.Sales_Region_Code__r.Name+SRJUn.Sales_Region__r.Business_Line__c , SRJUn);
                                                         system.debug(newMaplead);
                                                         
         }
            system.debug('test0');
        for(lead ld:Newlead){
            string ldZip;
            if(ld.Opportunity_Country__c == 'CA' && ld.Business_Line__c != 'WFS_CA'&& ld.Business_Line__c != 'WFS_US' && ld.Business_Line__c != 'ES CA'){
                ldZip = ld.Sales_Region_Code__c.substring(0,3).toUpperCase();
            } 
            else
            if(ld.Sales_Region_Code__c != null && ld.Sales_Region_Code__c != ''
               	&& ld.Business_Line__c != null &&  ld.Business_Line__c != '' && (ld.Opportunity_Country__c.toUpperCase() == 'US'||ld.Opportunity_Country__c.toUpperCase() == 'United States'||ld.Opportunity_Country__c.toUpperCase() == 'USA')
               ){
                  	ldZip = ld.Sales_Region_Code__c.substring(0,5).toUpperCase();
             	}
            else
			ldZip = ld.Sales_Region_Code__c;	
            if(newMaplead.containsKey(ldZip+ld.Business_Line__c)){
                system.debug(ldZip+ld.Business_Line__c);
                ld.Sales_Region__c = newMaplead.get(ldZip+ld.Business_Line__c).Sales_Region__r.Name;
                ld.Sales_Region_ID__c = newMaplead.get(ldZip+ld.Business_Line__c).Sales_Region__r.Id;
                ld.Inside_Sales_Rep_Email__c = newMaplead.get(ldZip+ld.Business_Line__c).Sales_Region__r.Inside_Sales_Rep__r.Email;
                ld.AD_Distribution_Group__c = newMaplead.get(ldZip+ld.Business_Line__c).Sales_Region__r.AD_Distribution_Group__c;
                
            }else{
                ld.Sales_Region__c = '';
                system.debug('test2');
            }
        }
            
        }catch(exception e){
            
            system.debug('8lead error88'+e.getStackTraceString())                                                                                                               ;
            
        }
        
        
    }
}