unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used to run price rules and approvals against this Quote.</description>
    <inlineHelpText>Indicate the Quote Type. Used to run Price Rules and Approvals against this Quote.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Associated_External_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Associated_External_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated External Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines (Associated External Quote Line)</relationshipLabel>
    <relationshipName>ExternalQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Associated_Partnership_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Associated_Partnership_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Partnership Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines (Partnership Quote Line)</relationshipLabel>
    <relationshipName>PartnershipQuoteLine</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Group__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Group to which this line belongs, if any.</description>
    <inlineHelpText>Group to which this line belongs, if any.</inlineHelpText>
    <label>Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Optional__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks this line as optional. Optional line items don't contribute to quote totals and are not transferred to the Opportunity.</description>
    <inlineHelpText>Marks this line as optional. Optional line items don't contribute to quote totals and are not transferred to the Opportunity.</inlineHelpText>
    <label>Optional</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line's product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Trans_Category__c.field-meta.xml
<CustomField>
    <fullName>Trans_Category__c</fullName>
    <description>Transaction Category read from the product on the quote line.  If the quote line is Sale/Rental then the Transaction Category is read from the Transaction Type of the Quote Line</description>
    <inlineHelpText>Transaction Category read from the product on the quote line.  If the quote line is Sale/Rental then the Transaction Category is read from the Transaction Type of the Quote Line</inlineHelpText>
    <label>Trans Category</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used in conjunction with Rental Price Rules &amp; Product Rule/Validations
Calc from Quote if QuoteLine group is blank</description>
    <formula>TEXT( SBQQ__Quote__r.Transaction_Type__c )</formula>
    <inlineHelpText>Transaction Type identified on the Quote or Line Group</inlineHelpText>
    <label>Transaction Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Data entry field for Contract Unit Price</description>
    <inlineHelpText>Data entry field for Contract Unit Price</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/SBQQ__QuoteLineGroup__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineGroupHelp</customHelpPage>
    <description>Group of line items on a quote.</description>
    <label>Quote Line Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/External__c.field-meta.xml
<CustomField>
    <fullName>External__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/External_Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>External_Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Quote Line Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Quote Line Groups (External Quote Line Group)</relationshipLabel>
    <relationshipName>Quote_Line_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/Joint_Venture_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Joint_Venture_Line_Items__c</fullName>
    <defaultValue>false</defaultValue>
    <label>3rd Party Partnership Line Items</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Optional__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks the entire group as optional.</description>
    <inlineHelpText>Marks the entire group as optional.</inlineHelpText>
    <label>Optional</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Quote to which this group belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
                <default>true</default>
                <label>Rental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/X3rd_Party_Partnership_Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partnership_Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3rd Party Partnership Quote Line Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Quote Line Groups (3rd Party Partnership Quote Line Group)</relationshipLabel>
    <relationshipName>Quote_Line_Groups2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <displayFormat>Transaction-{000000000}</displayFormat>
        <label>Transaction Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction_Type__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

unpackaged/main/default/objects/Transaction_Type__c/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <label>Sale</label>
</RecordType>

unpackaged/main/default/classes/QuoteLineGroupCloneHandler.cls
public class QuoteLineGroupCloneHandler {

    //public static Boolean isRunning = false;

    public static void processForQuotes(Set<Id> quoteIds) {
        system.debug('***isRunning**'+QuoteLineGroupRecurssionCheck.isRunning);
        system.debug('***quoteIds**'+quoteIds);
        if (QuoteLineGroupRecurssionCheck.isRunning) {
            return;
        }
        QuoteLineGroupRecurssionCheck.isRunning = true;

        try {
            if (quoteIds == null || quoteIds.isEmpty()) {
                return;
            }

            // 1) Get all external groups under these quotes
            List<SBQQ__QuoteLineGroup__c> externalGroups = [
                SELECT Id,
                       Name,
                       External__c,
                       External_Quote_Line_Group__c,
                       X3rd_Party_Partnership_Quote_Line_Group__c,
                       SBQQ__Quote__c,
                       SBQQ__Quote__r.Transaction_Type__c
                FROM SBQQ__QuoteLineGroup__c
                WHERE SBQQ__Quote__c IN :quoteIds
                  AND External__c = true
            ];

            if (externalGroups.isEmpty()) {
                return;
            }

            // 2) Clone only those that don't yet have an internal counterpart
            List<SBQQ__QuoteLineGroup__c> groupsToClone = new List<SBQQ__QuoteLineGroup__c>();
            for (SBQQ__QuoteLineGroup__c g : externalGroups) {
                if (g.External_Quote_Line_Group__c == null &&
                    g.X3rd_Party_Partnership_Quote_Line_Group__c == null) {
                    groupsToClone.add(g);
                }
            }

            List<SBQQ__QuoteLineGroup__c> newGroupsToInsert = new List<SBQQ__QuoteLineGroup__c>();
            Map<Id, Integer> originalIdToIndex = new Map<Id, Integer>();

            if (!groupsToClone.isEmpty()) {
                for (SBQQ__QuoteLineGroup__c orig : groupsToClone) {
                    SBQQ__QuoteLineGroup__c cloned = orig.clone(false, true, false, false);

                    if (cloned.Name != null) {
                        cloned.Name = cloned.Name + ' - Internal';
                    }

                    cloned.External__c = false;
                    cloned.SBQQ__Optional__c = true;
                    cloned.Joint_Venture_Line_Items__c = true;

                    cloned.External_Quote_Line_Group__c = null;
                    cloned.X3rd_Party_Partnership_Quote_Line_Group__c = null;

                    newGroupsToInsert.add(cloned);
                    originalIdToIndex.put(orig.Id, newGroupsToInsert.size() - 1);
                }

                insert newGroupsToInsert;
            }

            // 3) Build external -> internal group map (includes existing links + new ones)
            Map<Id, Id> externalToInternalGroup = new Map<Id, Id>();

            // a) For groups we just cloned
            for (Id extGroupId : originalIdToIndex.keySet()) {
                Integer idx = originalIdToIndex.get(extGroupId);
                externalToInternalGroup.put(extGroupId, newGroupsToInsert[idx].Id);
            }

            // b) For external groups that already had an internal group
            for (SBQQ__QuoteLineGroup__c g : externalGroups) {
                if (g.External_Quote_Line_Group__c != null &&
                    !externalToInternalGroup.containsKey(g.Id)) {
                    externalToInternalGroup.put(g.Id, g.External_Quote_Line_Group__c);
                }
            }

            // 4) Update original external groups with references to internal groups
            List<SBQQ__QuoteLineGroup__c> groupsToUpdate = new List<SBQQ__QuoteLineGroup__c>();
            for (SBQQ__QuoteLineGroup__c g : externalGroups) {
                if (g.External_Quote_Line_Group__c == null &&
                    externalToInternalGroup.containsKey(g.Id)) {
                    Id newInternalId = externalToInternalGroup.get(g.Id);
                    SBQQ__QuoteLineGroup__c upd = new SBQQ__QuoteLineGroup__c(
                        Id = g.Id,
                        External_Quote_Line_Group__c = newInternalId,
                        X3rd_Party_Partnership_Quote_Line_Group__c = newInternalId
                    );
                    groupsToUpdate.add(upd);
                }
            }
            if (!groupsToUpdate.isEmpty()) {
                update groupsToUpdate;
            }

            if (externalToInternalGroup.isEmpty()) {
                return;
            }

            // 5) Prepare for line cloning
            Set<Id> externalGroupIds = new Set<Id>(externalToInternalGroup.keySet());
            Set<Id> internalGroupIds = new Set<Id>(externalToInternalGroup.values());

            // 6) Query all external lines with all fields (dynamic SOQL)
            Map<String, Schema.SObjectField> fieldMap =
                Schema.SObjectType.SBQQ__QuoteLine__c.fields.getMap();
            List<String> fieldNames = new List<String>();
            fieldNames.addAll(fieldMap.keySet());

            Set<Id> extGroupIds = new Set<Id>(externalGroupIds);

            String soql = 'SELECT ' + String.join(fieldNames, ',') +
                          ' FROM SBQQ__QuoteLine__c' +
                          ' WHERE SBQQ__Group__c IN :extGroupIds';

            List<SBQQ__QuoteLine__c> externalLines = Database.query(soql);

            if (externalLines.isEmpty()) {
                return;
            }

            // Map external group Id -> group (for Transaction_Type__c)
            Map<Id, SBQQ__QuoteLineGroup__c> groupById =
                new Map<Id, SBQQ__QuoteLineGroup__c>(externalGroups);

            // 7) Two-pass cloning so SBQQ__RequiredBy__c points to cloned parents

            List<SBQQ__QuoteLine__c> parentClonesToInsert = new List<SBQQ__QuoteLine__c>();
            List<SBQQ__QuoteLine__c> childClonesToInsert  = new List<SBQQ__QuoteLine__c>();

            // Track new clones
            Map<Id, SBQQ__QuoteLine__c> parentOrigToCloneSObj =
                new Map<Id, SBQQ__QuoteLine__c>();
            Map<Id, SBQQ__QuoteLine__c> childOrigToCloneSObj =
                new Map<Id, SBQQ__QuoteLine__c>();

            // Map original parent → cloned parent Id (existing + new)
            Map<Id, Id> parentIdMap = new Map<Id, Id>();

            // 7a) Seed parentIdMap from existing clones via Associated_Partnership_Quote_Line__c
            for (SBQQ__QuoteLine__c origLine : externalLines) {
                if (origLine.SBQQ__RequiredBy__c == null &&  // parent
                    origLine.Associated_Partnership_Quote_Line__c != null) {

                    parentIdMap.put(
                        origLine.Id,
                        origLine.Associated_Partnership_Quote_Line__c
                    );
                }
            }

            // PASS 1: parents (RequiredBy__c == null, not already associated)
            for (SBQQ__QuoteLine__c origLine : externalLines) {
                Id extGroupId = origLine.SBQQ__Group__c;
                if (!externalToInternalGroup.containsKey(extGroupId)) {
                    continue;
                }

                // Skip parents that already have a partnership line
                if (origLine.Associated_Partnership_Quote_Line__c != null) {
                    continue;
                }

                if (origLine.SBQQ__RequiredBy__c != null) {
                    continue; // parents only
                }

                Id internalGroupId = externalToInternalGroup.get(extGroupId);
                if (internalGroupId == null) {
                    continue;
                }

                SBQQ__QuoteLine__c newLine =
                    origLine.clone(false, true, false, false);
                newLine.SBQQ__Group__c = internalGroupId;

                // Pricing logic for parents
                SBQQ__QuoteLineGroup__c extGroup = groupById.get(extGroupId);
                String txType = (extGroup != null)
                    ? extGroup.SBQQ__Quote__r.Transaction_Type__c
                    : null;
                Decimal origPrice = origLine.Unit_Price__c;

                if (txType != null &&
                    origPrice != null &&
                    origPrice > 0 &&
                    (origLine.Trans_Category__c == 'Rental' ||
                     origLine.Trans_Category__c == 'Sale' ||
                     origLine.Trans_Category__c == 'VAPS')) {

                    if (txType == 'Rental') {
                        newLine.Unit_Price__c = origPrice * 0.90; // 90%
                    } else if (txType == 'Sale') {
                        newLine.Unit_Price__c = origPrice * 0.97; // 3% less
                    }
                }

                System.debug(
                    'PARENT CLONE DEBUG → ORIG: ' + origLine.Id +
                    ', Orig Unit_Price__c=' + origPrice +
                    ', TxType=' + txType +
                    ', Clone Unit_Price__c=' + newLine.Unit_Price__c
                );

                parentClonesToInsert.add(newLine);
                parentOrigToCloneSObj.put(origLine.Id, newLine);
            }

            if (!parentClonesToInsert.isEmpty()) {
                insert parentClonesToInsert;
            }

            // Add newly cloned parents to parentIdMap
            for (Id origId : parentOrigToCloneSObj.keySet()) {
                parentIdMap.put(origId, parentOrigToCloneSObj.get(origId).Id);
            }

            // PASS 2: children (RequiredBy__c != null, not already associated)
            for (SBQQ__QuoteLine__c origLine : externalLines) {
                Id extGroupId = origLine.SBQQ__Group__c;
                if (!externalToInternalGroup.containsKey(extGroupId)) {
                    continue;
                }

                // Skip children that already have a partnership line
                if (origLine.Associated_Partnership_Quote_Line__c != null) {
                    continue;
                }

                if (origLine.SBQQ__RequiredBy__c == null) {
                    continue; // children only
                }

                Id internalGroupId = externalToInternalGroup.get(extGroupId);
                if (internalGroupId == null) {
                    continue;
                }

                SBQQ__QuoteLine__c newLine =
                    origLine.clone(false, true, false, false);
                newLine.SBQQ__Group__c = internalGroupId;

                // Remap RequiredBy__c to cloned parent if possible
                Id origParentId = origLine.SBQQ__RequiredBy__c;
                if (origParentId != null && parentIdMap.containsKey(origParentId)) {
                    newLine.SBQQ__RequiredBy__c = parentIdMap.get(origParentId);
                }

                // Pricing logic for children
                SBQQ__QuoteLineGroup__c extGroup = groupById.get(extGroupId);
                String txType = (extGroup != null)
                    ? extGroup.SBQQ__Quote__r.Transaction_Type__c
                    : null;
                Decimal origPrice = origLine.Unit_Price__c;

                if (txType != null &&
                    origPrice != null &&
                    origPrice > 0 &&
                    (origLine.Trans_Category__c == 'Rental' ||
                     origLine.Trans_Category__c == 'Sale' ||
                     origLine.Trans_Category__c == 'VAPS')) {

                    if (txType == 'Rental') {
                        newLine.Unit_Price__c = origPrice * 0.90; // 90%
                    } else if (txType == 'Sale') {
                        newLine.Unit_Price__c = origPrice * 0.97; // 3% less
                    }
                }

                System.debug(
                    'CHILD CLONE DEBUG → ORIG: ' + origLine.Id +
                    ', Orig Unit_Price__c=' + origPrice +
                    ', TxType=' + txType +
                    ', Clone Unit_Price__c=' + newLine.Unit_Price__c +
                    ', New RequiredBy__c=' + newLine.SBQQ__RequiredBy__c
                );

                childClonesToInsert.add(newLine);
                childOrigToCloneSObj.put(origLine.Id, newLine);
            }

            if (!childClonesToInsert.isEmpty()) {
                insert childClonesToInsert;
            }

            // 8) Populate Associated_* link fields on originals and clones

            Map<Id, Id> origToCloneId = new Map<Id, Id>();

            // parents
            for (Id origId : parentOrigToCloneSObj.keySet()) {
                origToCloneId.put(origId, parentOrigToCloneSObj.get(origId).Id);
            }
            // children
            for (Id origId : childOrigToCloneSObj.keySet()) {
                origToCloneId.put(origId, childOrigToCloneSObj.get(origId).Id);
            }

            if (!origToCloneId.isEmpty()) {
                List<SBQQ__QuoteLine__c> originalsToUpdate = new List<SBQQ__QuoteLine__c>();
                List<SBQQ__QuoteLine__c> clonesToUpdate    = new List<SBQQ__QuoteLine__c>();

                for (Id origId : origToCloneId.keySet()) {
                    Id cloneId = origToCloneId.get(origId);

                    // On original external line
                    originalsToUpdate.add(new SBQQ__QuoteLine__c(
                        Id = origId,
                        Associated_Partnership_Quote_Line__c = cloneId
                    ));

                    // On cloned internal line
                    clonesToUpdate.add(new SBQQ__QuoteLine__c(
                        Id = cloneId,
                        Associated_External_Quote_Line__c = origId
                    ));
                }

                if (!originalsToUpdate.isEmpty()) {
                    update originalsToUpdate;
                }
                if (!clonesToUpdate.isEmpty()) {
                    update clonesToUpdate;
                }
            }

        } finally {
           // isRunning = false;
        }
    }

    // Helper to build a uniqueness key for lines (currently unused but kept for future)
    private static String buildLineKey(Id groupId, Id productId, Decimal numberVal) {
        String g = (groupId == null) ? 'NONE' : String.valueOf(groupId);
        String p = (productId == null) ? 'NONE' : String.valueOf(productId);
        String n = (numberVal == null) ? 'NONE' : String.valueOf(numberVal);
        return g + '|' + p + '|' + n;
    }
}