unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used to run price rules and approvals against this Quote.</description>
    <inlineHelpText>Indicate the Quote Type. Used to run Price Rules and Approvals against this Quote.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Group__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Group to which this line belongs, if any.</description>
    <inlineHelpText>Group to which this line belongs, if any.</inlineHelpText>
    <label>Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Number__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Number__c</fullName>
    <description>Number indicating this line's position within its group or quote.</description>
    <inlineHelpText>Number indicating this line's position within its group or quote.</inlineHelpText>
    <label>Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Optional__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks this line as optional. Optional line items don't contribute to quote totals and are not transferred to the Opportunity.</description>
    <inlineHelpText>Marks this line as optional. Optional line items don't contribute to quote totals and are not transferred to the Opportunity.</inlineHelpText>
    <label>Optional</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line's product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Trans_Category__c.field-meta.xml
<CustomField>
    <fullName>Trans_Category__c</fullName>
    <description>Transaction Category read from the product on the quote line.  If the quote line is Sale/Rental then the Transaction Category is read from the Transaction Type of the Quote Line</description>
    <inlineHelpText>Transaction Category read from the product on the quote line.  If the quote line is Sale/Rental then the Transaction Category is read from the Transaction Type of the Quote Line</inlineHelpText>
    <label>Trans Category</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used in conjunction with Rental Price Rules &amp; Product Rule/Validations
Calc from Quote if QuoteLine group is blank</description>
    <formula>TEXT( SBQQ__Quote__r.Transaction_Type__c )</formula>
    <inlineHelpText>Transaction Type identified on the Quote or Line Group</inlineHelpText>
    <label>Transaction Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Data entry field for Contract Unit Price</description>
    <inlineHelpText>Data entry field for Contract Unit Price</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/SBQQ__QuoteLineGroup__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineGroupHelp</customHelpPage>
    <description>Group of line items on a quote.</description>
    <label>Quote Line Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/External__c.field-meta.xml
<CustomField>
    <fullName>External__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/External_Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>External_Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Quote Line Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Quote Line Groups (External Quote Line Group)</relationshipLabel>
    <relationshipName>Quote_Line_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/Joint_Venture_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Joint_Venture_Line_Items__c</fullName>
    <defaultValue>false</defaultValue>
    <label>3rd Party Partnership Line Items</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Number__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Number__c</fullName>
    <description>Sort order of this group within its quote.</description>
    <inlineHelpText>Sort order of this group within its quote.</inlineHelpText>
    <label>Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Optional__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks the entire group as optional.</description>
    <inlineHelpText>Marks the entire group as optional.</inlineHelpText>
    <label>Optional</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Quote to which this group belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
                <default>true</default>
                <label>Rental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/X3rd_Party_Partnership_Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partnership_Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3rd Party Partnership Quote Line Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Quote Line Groups (3rd Party Partnership Quote Line Group)</relationshipLabel>
    <relationshipName>Quote_Line_Groups2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <displayFormat>Transaction-{000000000}</displayFormat>
        <label>Transaction Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction_Type__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

unpackaged/main/default/objects/Transaction_Type__c/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <label>Sale</label>
</RecordType>

unpackaged/main/default/classes/ExternalQuoteLineGroupCloneJob.cls
public class ExternalQuoteLineGroupCloneJob implements Queueable {

    private Set<Id> groupIds;

    public ExternalQuoteLineGroupCloneJob(Set<Id> groupIds) {
        this.groupIds = groupIds;
    }

    public void execute(QueueableContext context) {
        if (groupIds == null || groupIds.isEmpty()) {
            return;
        }

        // 1) Query external groups
        List<SBQQ__QuoteLineGroup__c> externalGroups = [
            SELECT Id,
                   Name,
                   External__c,
                   External_Quote_Line_Group__c,
                   X3rd_Party_Partnership_Quote_Line_Group__c,
                   SBQQ__Quote__c,
                   SBQQ__Quote__r.Transaction_Type__c
            FROM SBQQ__QuoteLineGroup__c
            WHERE Id IN :groupIds
              AND External__c = true
        ];

        if (externalGroups.isEmpty()) {
            return;
        }

        // 2) Clone external groups that don't yet have an internal counterpart
        List<SBQQ__QuoteLineGroup__c> groupsToClone = new List<SBQQ__QuoteLineGroup__c>();
        for (SBQQ__QuoteLineGroup__c g : externalGroups) {
            if (g.External_Quote_Line_Group__c == null &&
                g.X3rd_Party_Partnership_Quote_Line_Group__c == null) {
                groupsToClone.add(g);
            }
        }

        List<SBQQ__QuoteLineGroup__c> newGroupsToInsert = new List<SBQQ__QuoteLineGroup__c>();
        Map<Id, Integer> originalIdToIndex = new Map<Id, Integer>();

        if (!groupsToClone.isEmpty()) {
            for (SBQQ__QuoteLineGroup__c orig : groupsToClone) {
                SBQQ__QuoteLineGroup__c cloned = orig.clone(false, true, false, false);

                if (cloned.Name != null) {
                    cloned.Name = cloned.Name + ' - Internal';
                }

                cloned.External__c = false;
                cloned.SBQQ__Optional__c = true;
                cloned.Joint_Venture_Line_Items__c = true;

                cloned.External_Quote_Line_Group__c = null;
                cloned.X3rd_Party_Partnership_Quote_Line_Group__c = null;

                newGroupsToInsert.add(cloned);
                originalIdToIndex.put(orig.Id, newGroupsToInsert.size() - 1);
            }

            insert newGroupsToInsert;
        }

        // 3) Build external -> internal group map
        Map<Id, Id> externalToInternalGroup = new Map<Id, Id>();

        // a) Newly cloned ones
        for (Id extGroupId : originalIdToIndex.keySet()) {
            Integer idx = originalIdToIndex.get(extGroupId);
            externalToInternalGroup.put(extGroupId, newGroupsToInsert[idx].Id);
        }

        // b) Ones that already had internal linked
        for (SBQQ__QuoteLineGroup__c g : externalGroups) {
            if (g.External_Quote_Line_Group__c != null &&
                !externalToInternalGroup.containsKey(g.Id)) {
                externalToInternalGroup.put(g.Id, g.External_Quote_Line_Group__c);
            }
        }

        // 4) Update original external groups with references to internal group
        List<SBQQ__QuoteLineGroup__c> groupsToUpdate = new List<SBQQ__QuoteLineGroup__c>();
        for (SBQQ__QuoteLineGroup__c g : externalGroups) {
            if (g.External_Quote_Line_Group__c == null &&
                externalToInternalGroup.containsKey(g.Id)) {

                Id internalId = externalToInternalGroup.get(g.Id);
                groupsToUpdate.add(new SBQQ__QuoteLineGroup__c(
                    Id = g.Id,
                    External_Quote_Line_Group__c = internalId,
                    X3rd_Party_Partnership_Quote_Line_Group__c = internalId
                ));
            }
        }
        if (!groupsToUpdate.isEmpty()) {
            update groupsToUpdate;
        }

        if (externalToInternalGroup.isEmpty()) {
            return;
        }

        // 5) Clone lines: parents first, then children with RequiredBy remap

        Set<Id> externalGroupIds = new Set<Id>(externalToInternalGroup.keySet());
        Set<Id> internalGroupIds = new Set<Id>(externalToInternalGroup.values());

        // Existing lines in internal groups (avoid duplicates)
        Set<String> existingKeys = new Set<String>();
        if (!internalGroupIds.isEmpty()) {
            for (SBQQ__QuoteLine__c existing : [
                SELECT Id, SBQQ__Group__c, SBQQ__Product__c, SBQQ__Number__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Group__c IN :internalGroupIds
            ]) {
                existingKeys.add(buildLineKey(
                    existing.SBQQ__Group__c,
                    existing.SBQQ__Product__c,
                    existing.SBQQ__Number__c
                ));
            }
        }

        // Query ALL fields for external lines so clone() carries everything
        Map<String, Schema.SObjectField> fieldMap =
            Schema.SObjectType.SBQQ__QuoteLine__c.fields.getMap();
        List<String> fieldNames = new List<String>(fieldMap.keySet());

        Set<Id> extGroupIds = new Set<Id>(externalGroupIds);

        String soql =
            'SELECT ' + String.join(fieldNames, ',') +
            ' FROM SBQQ__QuoteLine__c' +
            ' WHERE SBQQ__Group__c IN :extGroupIds';

        List<SBQQ__QuoteLine__c> externalLines = Database.query(soql);

        if (externalLines.isEmpty()) {
            return;
        }

        // Map group Id -> group (for Transaction_Type__c)
        Map<Id, SBQQ__QuoteLineGroup__c> groupById =
            new Map<Id, SBQQ__QuoteLineGroup__c>(externalGroups);

        List<SBQQ__QuoteLine__c> parentClonesToInsert = new List<SBQQ__QuoteLine__c>();
        List<SBQQ__QuoteLine__c> childClonesToInsert  = new List<SBQQ__QuoteLine__c>();
        Set<String> newKeys = new Set<String>();

        Map<Id, SBQQ__QuoteLine__c> parentOrigToCloneSObj = new Map<Id, SBQQ__QuoteLine__c>();

        // PASS 1: parents (no RequiredBy)
        for (SBQQ__QuoteLine__c orig : externalLines) {
            Id extGroupId = orig.SBQQ__Group__c;
            if (!externalToInternalGroup.containsKey(extGroupId)) {
                continue;
            }
            if (orig.SBQQ__RequiredBy__c != null) {
                continue;
            }

            Id internalGroupId = externalToInternalGroup.get(extGroupId);

            String key = buildLineKey(
                internalGroupId,
                orig.SBQQ__Product__c,
                orig.SBQQ__Number__c
            );

            if (existingKeys.contains(key) || newKeys.contains(key)) {
                continue;
            }

            SBQQ__QuoteLine__c cloneLine = orig.clone(false, true, false, false);
            cloneLine.SBQQ__Group__c = internalGroupId;

            // Pricing logic (parents)
            SBQQ__QuoteLineGroup__c grp = groupById.get(extGroupId);
            String txType = (grp != null) ? grp.SBQQ__Quote__r.Transaction_Type__c : null;
            Decimal origPrice = orig.Unit_Price__c;

            if (txType != null &&
                origPrice != null &&
                origPrice > 0 &&
                (orig.Trans_Category__c == 'Rental' ||
                 orig.Trans_Category__c == 'Sale')) {

                if (txType == 'Rental') {
                    cloneLine.Unit_Price__c = origPrice * 0.90;
                } else if (txType == 'Sale') {
                    cloneLine.Unit_Price__c = origPrice * 0.97;
                }
            }

            parentClonesToInsert.add(cloneLine);
            newKeys.add(key);
            parentOrigToCloneSObj.put(orig.Id, cloneLine);
        }

        if (!parentClonesToInsert.isEmpty()) {
            insert parentClonesToInsert;
        }

        // Map original parent Id -> cloned parent Id
        Map<Id, Id> parentOrigToCloneId = new Map<Id, Id>();
        for (Id origId : parentOrigToCloneSObj.keySet()) {
            parentOrigToCloneId.put(origId, parentOrigToCloneSObj.get(origId).Id);
        }

        // PASS 2: children (with RequiredBy remapped)
        for (SBQQ__QuoteLine__c orig : externalLines) {
            Id extGroupId = orig.SBQQ__Group__c;
            if (!externalToInternalGroup.containsKey(extGroupId)) {
                continue;
            }
            if (orig.SBQQ__RequiredBy__c == null) {
                continue;
            }

            Id internalGroupId = externalToInternalGroup.get(extGroupId);

            String key = buildLineKey(
                internalGroupId,
                orig.SBQQ__Product__c,
                orig.SBQQ__Number__c
            );

            if (existingKeys.contains(key) || newKeys.contains(key)) {
                continue;
            }

            SBQQ__QuoteLine__c cloneLine = orig.clone(false, true, false, false);
            cloneLine.SBQQ__Group__c = internalGroupId;

            // Remap RequiredBy
            Id origParentId = orig.SBQQ__RequiredBy__c;
            if (origParentId != null && parentOrigToCloneId.containsKey(origParentId)) {
                cloneLine.SBQQ__RequiredBy__c = parentOrigToCloneId.get(origParentId);
            }

            // Pricing logic (children)
            SBQQ__QuoteLineGroup__c grp = groupById.get(extGroupId);
            String txType = (grp != null) ? grp.SBQQ__Quote__r.Transaction_Type__c : null;
            Decimal origPrice = orig.Unit_Price__c;

            if (txType != null &&
                origPrice != null &&
                origPrice > 0 &&
                (orig.Trans_Category__c == 'Rental' ||
                 orig.Trans_Category__c == 'Sale')) {

                if (txType == 'Rental') {
                    cloneLine.Unit_Price__c = origPrice * 0.90;
                } else if (txType == 'Sale') {
                    cloneLine.Unit_Price__c = origPrice * 0.97;
                }
            }

            childClonesToInsert.add(cloneLine);
            newKeys.add(key);
        }

        if (!childClonesToInsert.isEmpty()) {
            insert childClonesToInsert;
        }
    }

    // Uniqueness key helper
    private static String buildLineKey(Id groupId, Id productId, Decimal numberVal) {
        String g = (groupId == null) ? 'NONE' : String.valueOf(groupId);
        String p = (productId == null) ? 'NONE' : String.valueOf(productId);
        String n = (numberVal == null) ? 'NONE' : String.valueOf(numberVal);
        return g + '|' + p + '|' + n;
    }
}