unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Used for Branding</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <label>Brand Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <label>Brand Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/classes/BrandTriggerHandlerTest.cls
@isTest(seealldata=false)
public class BrandTriggerHandlerTest{
   @isTest static void BrandTriggerHandlerMethod(){
        Brand__c b = new Brand__c();
        b.Name = 'BOXX Modular';
        b.Brand_Code__c = 'BOXX';
        insert b;
        
        Lead l = new Lead();
        l.Brand_Code__c = 'BOXX';
        l.FirstName = 'test';
        l.LastName = 'test';
        insert l;
    }
    

}