unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Used for Branding</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <label>Brand Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <label>Brand Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Code__c</fullName>
    <label>Sales Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>New Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/objects/Sales_Region_Code__c/Sales_Region_Code__c.object-meta.xml
<CustomObject>
    <label>Sales Region Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Region Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/BrandTriggerHandler.cls
public class BrandTriggerHandler {
	public static void brandHandler(list<lead> Newlead){
        try{
        	 	set<string> brandCode = new set<string>();
				Map<string,Brand__c> newMapBrand = new map<string,Brand__c>();
        		for(Lead lead:Newlead)
                {	
					system.debug('Enter For'+lead.Brand_Code__c);            
            		if(lead.Brand_Code__c != null && lead.Sales_Region_Code__c != '')
                    {
                  	 	brandCode.add(lead.Brand_Code__c);
                   		system.debug('Brand Code is: '+brandCode);
             		}
          		}
            
             for(Brand__c BR:[select id, Brand_Code__c from Brand__c
                  				where  Brand_Code__c IN: brandCode]){
                                                         system.debug(BR.Brand_Code__c );
                                                         newMapBrand.put(BR.Brand_Code__c , BR);
                                                         system.debug(newMapBrand);
                                                         
        	 }
            
            for(lead ld:Newlead){
            string ldBrand;
			ldBrand = ld.Brand_Code__c;	
            if(newMapBrand.containsKey(ldBrand)){
                system.debug(ldBrand);
                ld.Brand_Name__c = newMapBrand.get(ldBrand).Id;
            }else{
                ld.Brand_Name__c = '';
                system.debug('test2');
            }
        }
    
        
        }catch(exception e){
            
            system.debug('8lead error88'+e.getStackTraceString());
            
        }
    }
}