unpackaged/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Black Diamond Branch List</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Branch__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Branches</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <description>Used to inform Price Rules for Purchases and Rentals. Branch matches to same field on Price List object to assist with proper pricing reference.</description>
    <formula>SBQQ__Opportunity2__r.Branch_Name_Text__c</formula>
    <inlineHelpText>Branch selected on the related Opportunity record</inlineHelpText>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Used to prorate eligible products by month. For WFS, combined with Billable Days.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used to run price rules and approvals against this Quote.</description>
    <inlineHelpText>Indicate the Quote Type. Used to run Price Rules and Approvals against this Quote.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/recordTypes/BOXX.recordType-meta.xml
<RecordType>
    <fullName>BOXX</fullName>
    <active>true</active>
    <label>BOXX</label>
</RecordType>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/CLM_Install_Revenue__c.field-meta.xml
<CustomField>
    <fullName>CLM_Install_Revenue__c</fullName>
    <label>CLM Install Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/CLM_Transportation_Revenue__c.field-meta.xml
<CustomField>
    <fullName>CLM_Transportation_Revenue__c</fullName>
    <label>CLM Transportation Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/CLM_Unit_Revenue__c.field-meta.xml
<CustomField>
    <fullName>CLM_Unit_Revenue__c</fullName>
    <label>CLM Unit Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/CLM_VAPS_Revenue__c.field-meta.xml
<CustomField>
    <fullName>CLM_VAPS_Revenue__c</fullName>
    <label>CLM VAPS Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__NetTotal__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetTotal__c</fullName>
    <description>Net total price for this quote line item.</description>
    <formula>IF(AND(SBQQ__Renewal__c, !SBQQ__Existing__c, ISBLANK(SBQQ__PriorQuantity__c)), 0, SBQQ__NetPrice__c * SBQQ__EffectiveQuantity__c)</formula>
    <inlineHelpText>Net total price for this quote line item.</inlineHelpText>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line's product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term for the subscription product in this line. If the product is not a subscription this value has no effect.</description>
    <inlineHelpText>Term for this subscription. If this product is not a subscription this value has no effect.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Subscription_Term_Quote__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Term_Quote__c</fullName>
    <description>Term populated from the Quote using Process Builder flow</description>
    <inlineHelpText>Term populated from the Quote using Process Builder flow</inlineHelpText>
    <label>Subscription Term Quote</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used in conjunction with Rental Price Rules &amp; Product Rule/Validations
Calc from Quote if QuoteLine group is blank</description>
    <formula>TEXT( SBQQ__Quote__r.Transaction_Type__c )</formula>
    <inlineHelpText>Transaction Type identified on the Quote or Line Group</inlineHelpText>
    <label>Transaction Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Data entry field for Contract Unit Price</description>
    <inlineHelpText>Data entry field for Contract Unit Price</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <displayFormat>Transaction-{000000000}</displayFormat>
        <label>Transaction Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction_Type__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

unpackaged/main/default/globalValueSets/Branches.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUS Brisbane</fullName>
    </customValue>
    <customValue>
        <fullName>AUS Melbourne</fullName>
    </customValue>
    <customValue>
        <fullName>AUS Perth</fullName>
    </customValue>
    <customValue>
        <fullName>AUS Sydney</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Banks Dallas</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Edmonton</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Fort Worth</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Houston</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Kelowna</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Langley</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Nanaimo</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Ottawa</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Prince George</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Saskatchewan</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Stoney Creek</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX Vanguard</fullName>
    </customValue>
    <customValue>
        <fullName>Camps East</fullName>
    </customValue>
    <customValue>
        <fullName>Camps US</fullName>
    </customValue>
    <customValue>
        <fullName>Camps West</fullName>
    </customValue>
    <customValue>
        <fullName>ES Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>ES Estevan</fullName>
    </customValue>
    <customValue>
        <fullName>ES Fort St John</fullName>
    </customValue>
    <customValue>
        <fullName>ES Grande Prairie</fullName>
    </customValue>
    <customValue>
        <fullName>ES North Dakota</fullName>
    </customValue>
    <customValue>
        <fullName>ES Texas</fullName>
    </customValue>
    <customValue>
        <fullName>Head Office</fullName>
    </customValue>
    <customValue>
        <fullName>Horn River Lodge</fullName>
    </customValue>
    <customValue>
        <fullName>Little Prairie Lodge</fullName>
    </customValue>
    <customValue>
        <fullName>BOXX CL Martin</fullName>
    </customValue>
    <description>Black Diamond Branches</description>
    <masterLabel>Branches</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CLMRevenueHandler.cls
public with sharing class CLMRevenueHandler {
    public static Boolean isRunning = false;

    // Configure the labels you described (case-insensitive; we compare after lowercasing)
    private static final Set<String> INSTALL_NAMES = new Set<String>{ 'Install - Transactional Business', 'Dismantle' };
    private static final Set<String> TRANSPORT_NAMES = new Set<String>{ 'Transportation and Relocation', 'Return Transportation' };
    private static final Set<String> VAPS_NAMES = new Set<String>{ 'Miscellaneous Items' };   

    /**
     * Recalculates CLM_* revenue fields on the parent "Complex" Quote Line(s),
     * based on child/options linked via SBQQ__RequiredBy__c.
     *
     * Runs ONLY when the parent line's Quote has:
     *  - Branch__c = 'BOXX CL Martin'
     *  - Transaction_Type__c = 'Rental'
     *
     * Buckets:
     *  - Install Revenue:     sum(Unit_Price__c) for products exactly named Install or Dismantle
     *  - Transportation Rev:  sum(Unit_Price__c) for products exactly named Transportation or Return Transportation
     *  - VAPS Revenue:        sum(Unit_Price__c * Subscription_Term_Quote__c) for remaining non-Unit lines
     *  - Unit Revenue:        SBQQ__NetTotal__c - (Install + Transportation + VAPS)
     */
    public static void recalculate(Set<Id> parentComplexLineIds) {
        if (parentComplexLineIds == null || parentComplexLineIds.isEmpty()) return;

        isRunning = true;
        try {
            // 1) Query parents + quote context needed for eligibility + term + net total
            Map<Id, SBQQ__QuoteLine__c> parentsById = new Map<Id, SBQQ__QuoteLine__c>([
                SELECT Id,
                       SBQQ__Quote__c,
                       SBQQ__NetTotal__c,
                       CLM_Install_Revenue__c,
                       CLM_Transportation_Revenue__c,
                       CLM_VAPS_Revenue__c,
                       CLM_Unit_Revenue__c,
                       SBQQ__Quote__r.Branch__c,
                       SBQQ__Quote__r.Transaction_Type__c,
                       SBQQ__Quote__r.SBQQ__SubscriptionTerm__c
                FROM SBQQ__QuoteLine__c
                WHERE Id IN :parentComplexLineIds
            ]);

            if (parentsById.isEmpty()) return;

            // 2) Determine eligible parents and capture term per parent
            Set<Id> eligibleParentIds = new Set<Id>();
            Map<Id, Integer> termByParentId = new Map<Id, Integer>();

            for (SBQQ__QuoteLine__c p : parentsById.values()) {
                if (p.SBQQ__Quote__r.Branch__c == 'BOXX CL Martin'
                    && p.SBQQ__Quote__r.Transaction_Type__c == 'Rental'
                ) {
                    eligibleParentIds.add(p.Id);

                    Integer term = (Integer)p.SBQQ__Quote__r.SBQQ__SubscriptionTerm__c;
                    if (term == null || term < 0) term = 0;
                    termByParentId.put(p.Id, term);
                }
            }

            if (eligibleParentIds.isEmpty()) return;

            // 3) Pull all children linked to those parents
            List<SBQQ__QuoteLine__c> children = [
                SELECT Id,
                       SBQQ__RequiredBy__c,
                       Unit_Price__c,
                       SBQQ__Product__r.Name
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__RequiredBy__c IN :eligibleParentIds
            ];

            // 4) Compute totals per parent
            Map<Id, Decimal> installTotalByParent   = new Map<Id, Decimal>();
            Map<Id, Decimal> transportTotalByParent = new Map<Id, Decimal>();
            Map<Id, Decimal> vapsTotalByParent      = new Map<Id, Decimal>();

            for (SBQQ__QuoteLine__c c : children) {
                if (c.SBQQ__RequiredBy__c == null) continue;

                Decimal price = (c.Unit_Price__c == null) ? 0 : c.Unit_Price__c;

                String productName = (c.SBQQ__Product__r != null && c.SBQQ__Product__r.Name != null)
                    ? c.SBQQ__Product__r.Name.trim()
                    : '';

                String lower = normalize(productName);

                // Exclude "Unit" lines from these buckets (your unit revenue is derived from net total)
                if (lower.contains('unit')) {
                    continue;
                }

                // Install / Dismantle (one-time)
                if (matchesAnyExact(lower, INSTALL_NAMES)) {
                    installTotalByParent.put(
                        c.SBQQ__RequiredBy__c,
                        (installTotalByParent.containsKey(c.SBQQ__RequiredBy__c) ? installTotalByParent.get(c.SBQQ__RequiredBy__c) : 0) + price
                    );
                    continue;
                }

                // Transportation / Return Transportation (one-time)
                if (matchesAnyExact(lower, TRANSPORT_NAMES)) {
                    transportTotalByParent.put(
                        c.SBQQ__RequiredBy__c,
                        (transportTotalByParent.containsKey(c.SBQQ__RequiredBy__c) ? transportTotalByParent.get(c.SBQQ__RequiredBy__c) : 0) + price
                    );
                    continue;
                }

                // Bucket: VAPS (monthly rental) – treat everything else (non-unit, non-install, non-transport) as VAPS
                // If you have a better discriminator (Product Code, Family, checkbox), swap this logic.
                 if (matchesAnyExact(lower, VAPS_NAMES)) {
                	Integer term = termByParentId.get(c.SBQQ__RequiredBy__c);
                	Decimal extended = price * term;

                	vapsTotalByParent.put(
                    	c.SBQQ__RequiredBy__c,
                    	(vapsTotalByParent.containsKey(c.SBQQ__RequiredBy__c) ? vapsTotalByParent.get(c.SBQQ__RequiredBy__c) : 0) + extended
                	);
            	}
            }

            // 5) Update eligible parents
            List<SBQQ__QuoteLine__c> updates = new List<SBQQ__QuoteLine__c>();

            for (Id parentId : eligibleParentIds) {
                Decimal install = installTotalByParent.containsKey(parentId) ? installTotalByParent.get(parentId) : 0;
                Decimal trans   = transportTotalByParent.containsKey(parentId) ? transportTotalByParent.get(parentId) : 0;
                Decimal vaps    = vapsTotalByParent.containsKey(parentId) ? vapsTotalByParent.get(parentId) : 0;

                Decimal parentNetTotal = parentsById.get(parentId).SBQQ__NetTotal__c == null
                    ? 0
                    : parentsById.get(parentId).SBQQ__NetTotal__c;

                Decimal unitRevenue = parentNetTotal - (install + trans + vaps);

                updates.add(new SBQQ__QuoteLine__c(
                    Id = parentId,
                    CLM_Install_Revenue__c = install,
                    CLM_Transportation_Revenue__c = trans,
                    CLM_VAPS_Revenue__c = vaps,
                    CLM_Unit_Revenue__c = unitRevenue
                ));
            }

            if (!updates.isEmpty()) {
                update updates;
            }
        } finally {
            isRunning = false;
        }
    }

    // Normalizes a product name for matching: lowercase, collapse whitespace, trim
    private static String normalize(String s) {
        if (s == null) return '';
        return s.toLowerCase().replaceAll('\\s+', ' ').trim();
    }

    // Exact match against a set of expected names (after normalize())
    private static Boolean matchesAnyExact(String normalizedLowerName, Set<String> expectedLower) {
        if (String.isBlank(normalizedLowerName)) return false;
        for (String e : expectedLower) {
            if (normalizedLowerName == e) return true;
        }
        return false;
    }
}