unpackaged/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <description>Object used for SAP integration.</description>
    <label>Fleet</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fleet__c/fields/Rental_Status__c.field-meta.xml
<CustomField>
    <fullName>Rental_Status__c</fullName>
    <label>Rental Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Recurring Non-Rental</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <description>Name for this Quote. Used to indicate version.</description>
    <inlineHelpText>Name used to indicate Quote version.</inlineHelpText>
    <label>Quote Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Designates this quote as the Primary Quote for the related Opportunity. (Updates the related Opportunity's Actual Contract Value with Net Total from this Quote and the related Opportunity's Lines with Quote Lines from this Quote.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Used to prorate eligible products by month. For WFS, combined with Billable Days.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used to run price rules and approvals against this Quote.</description>
    <inlineHelpText>Indicate the Quote Type. Used to run Price Rules and Approvals against this Quote.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Transaction_Type_Detail__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type_Detail__c</fullName>
    <description>Used to populate reporting.</description>
    <inlineHelpText>Specify details about the Quote Type. Used to populate reporting. If Quote contains New and Fleet, choose Fleet.</inlineHelpText>
    <label>Transaction Type Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Existing Fleet Rental</fullName>
                <label>Fleet Rental</label>
            </value>
            <value>
                <fullName>New Fleet Rental</fullName>
                <label>New Rental</label>
            </value>
            <value>
                <fullName>Existing Fleet Sale</fullName>
                <label>Fleet Sale</label>
            </value>
            <value>
                <fullName>New Fleet Sale</fullName>
                <label>New Sale</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Pay All</fullName>
            </value>
            <value>
                <fullName>Pay at TOD</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__PricebookEntryId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricebookEntryId__c</fullName>
    <label>Pricebook Entry Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term for the subscription product in this line. If the product is not a subscription this value has no effect.</description>
    <inlineHelpText>Term for this subscription. If this product is not a subscription this value has no effect.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Used in conjunction with Rental Price Rules &amp; Product Rule/Validations
Calc from Quote if QuoteLine group is blank</description>
    <formula>TEXT( SBQQ__Quote__r.Transaction_Type__c )</formula>
    <inlineHelpText>Transaction Type identified on the Quote or Line Group</inlineHelpText>
    <label>Transaction Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup of the fleet item corresponding to this product/quote line item</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2)</booleanFilter>
        <filterItems>
            <field>Fleet__c.Rental_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Fleet__c.WIP_Asset__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Data entry field for Contract Unit Price</description>
    <inlineHelpText>Data entry field for Contract Unit Price</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <displayFormat>Transaction-{000000000}</displayFormat>
        <label>Transaction Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction_Type__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

unpackaged/main/default/classes/FleetCheckedOutServiceTest.cls
@IsTest
private class FleetCheckedOutServiceTest {
    @IsTest
    static void testCheckedOutUnits() {
        // Account & Opp
        Account a = new Account(Name = 'Acme');
        insert a;
        
        //Fetching Standard Pricebook
        Id stdPbId = Test.getStandardPricebookId();

        // Custom active pricebook (don’t depend on Standard PB)
        Pricebook2 pb = new Pricebook2(Name = 'Test PB', IsActive = true);
        insert pb;

        // Product & PBE
        Product2 prod = new Product2(Name = 'Test Rental Product', ProductCode = 'RENT-001', IsActive = true);
        insert prod;
        
        PricebookEntry pbestd = new PricebookEntry(
            Product2Id = prod.Id,
            Pricebook2Id = stdPbId,
            UnitPrice = 100,
            IsActive = true
        );
        insert pbestd;
        

        PricebookEntry pbe = new PricebookEntry(Product2Id = prod.Id, Pricebook2Id = pb.Id, UnitPrice = 100, IsActive = true);
        insert pbe;

        Opportunity o = new Opportunity(
            Name = 'Test Opp',
            StageName = 'Qualified',
            CloseDate = System.today().addDays(30),
            Pricebook2Id = pb.Id,
            AccountId = a.Id
        );
        insert o;

        // Primary Quote — point it to the same PB
        SBQQ__Quote__c q = new SBQQ__Quote__c(
            Quote_Name__c = 'Primary',
            SBQQ__Primary__c = true,
            SBQQ__Opportunity2__c = o.Id,
            Transaction_Type__c = 'Rental',
            Transaction_Type_Detail__c= 'Fleet Rental',
            SBQQ__SubscriptionTerm__c = 24
        );
        insert q;

        // Fleet units
        Fleet__c u1 = new Fleet__c(Name='Unit A', Rental_Status__c='Checked Out');
        Fleet__c u2 = new Fleet__c(Name='Unit B', Rental_Status__c='Available');
        insert new List<Fleet__c>{u1, u2};

        // Quote lines — use CPQ field API names
        SBQQ__QuoteLine__c ql1 = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = q.Id,
            SBQQ__Product__c = prod.Id,
            SBQQ__Quantity__c = 1,
            Unit_Price__c = 100,
            SBQQ__PricebookEntryId__c = pbe.Id,
            Unit__c = u1.Id // Checked Out
        );
        SBQQ__QuoteLine__c ql2 = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = q.Id,
            SBQQ__Product__c = prod.Id,
            SBQQ__Quantity__c = 1,
            Unit_Price__c = 100,
            SBQQ__PricebookEntryId__c = pbe.Id,
            Unit__c = u2.Id // Available
        );
        insert new List<SBQQ__QuoteLine__c>{ ql1, ql2 };

        Test.startTest();
        FleetCheckedOutService.Result res =
            FleetCheckedOutService.getCheckedOutUnitsForOpportunity(o.Id);
        Test.stopTest();

        System.assertEquals(true, res.hasCheckedOut, 'Should detect checked-out units');
        System.assertEquals(1, res.units.size(), 'Only one unit is checked-out');
        System.assertEquals(u1.Id, res.units[0].unitId);
        System.assertEquals('Checked Out', res.units[0].rentalStatus);
    }
}