unpackaged/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <description>Object used for SAP integration.</description>
    <label>Fleet</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fleet__c/fields/Rental_Status__c.field-meta.xml
<CustomField>
    <fullName>Rental_Status__c</fullName>
    <label>Rental Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Designates this quote as the Primary Quote for the related Opportunity. (Updates the related Opportunity's Actual Contract Value with Net Total from this Quote and the related Opportunity's Lines with Quote Lines from this Quote.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Group__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Group to which this line belongs, if any.</description>
    <inlineHelpText>Group to which this line belongs, if any.</inlineHelpText>
    <label>Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup of the fleet item corresponding to this product/quote line item</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2)</booleanFilter>
        <filterItems>
            <field>Fleet__c.Rental_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Fleet__c.WIP_Asset__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/SBQQ__QuoteLineGroup__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineGroupHelp</customHelpPage>
    <description>Group of line items on a quote.</description>
    <label>Quote Line Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/External__c.field-meta.xml
<CustomField>
    <fullName>External__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Quote to which this group belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FleetCheckedOutService.cls
// File: force-app/main/default/classes/FleetCheckedOutService.cls
public with sharing class FleetCheckedOutService {
    public class CheckedOutUnit {
        @AuraEnabled public Id unitId;
        @AuraEnabled public String unitName;
        @AuraEnabled public String rentalStatus;
    }
    public class Result {
        @AuraEnabled public Boolean hasCheckedOut;
        @AuraEnabled public List<CheckedOutUnit> units;
    }

    @AuraEnabled(cacheable=true)
    public static Result getCheckedOutUnitsForOpportunity(Id opportunityId) {
        Result r = new Result();
        r.units = new List<CheckedOutUnit>();
        if (opportunityId == null) { r.hasCheckedOut = false; return r; }

        // Query quote lines by walking up to the primary quote on this opportunity.
        // This avoids a separate "find primary quote" query and is more robust in tests & prod.
        List<SBQQ__QuoteLine__c> lines = [
            SELECT Id,
                   Unit__c,
                   Unit__r.Name,
                   Unit__r.Rental_Status__c
            FROM SBQQ__QuoteLine__c
            WHERE SBQQ__Quote__r.SBQQ__Opportunity2__c = :opportunityId
              AND SBQQ__Quote__r.SBQQ__Primary__c = true
              AND Unit__c != null
              AND Unit__r.Rental_Status__c = 'Checked Out'
              AND SBQQ__Group__r.External__c != true
            ORDER BY Unit__r.Name
        ];

        for (SBQQ__QuoteLine__c ql : lines) {
            CheckedOutUnit cu = new CheckedOutUnit();
            cu.unitId = ql.Unit__c;
            cu.unitName = ql.Unit__r.Name;
            cu.rentalStatus = ql.Unit__r.Rental_Status__c;
            r.units.add(cu);
        }
        r.hasCheckedOut = !r.units.isEmpty();
        return r;
    }
}