unpackaged/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <description>Object used for SAP integration.</description>
    <label>Fleet</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fleet__c/fields/CountUsed__c.field-meta.xml
<CustomField>
    <fullName>CountUsed__c</fullName>
    <label>Count Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Contract_Expired__c.field-meta.xml
<CustomField>
    <fullName>Contract_Expired__c</fullName>
    <formula>IF( Contract_End_Date__c &lt; Today(),TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Expired</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup of the fleet item corresponding to this product/quote line item</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2)</booleanFilter>
        <filterItems>
            <field>Fleet__c.Rental_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Fleet__c.WIP_Asset__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FleetCountTriggerHandler.cls
public class FleetCountTriggerHandler {
    public static void fleetCountAfterInsert(list<String> lstFleet){
		system.debug('***In the fleetCountAfterInsert method Performing Update/Insert***'+lstFleet);
        getFleetCount(lstFleet,'');
    }
     public static void fleetCountBeforeDelete(list<String> lstFleet){
        system.debug('***In the Before Delete method***'+lstFleet);
        getFleetCount(lstFleet,'Delete');
    }
    public static void fleetCountAfterUpdateOld(list<String> lstFleet){
        system.debug('***In the AfterUpdateOld method***'+lstFleet);
        getFleetCountOld(lstFleet,'Delete');
    }
    
    public static void getFleetCount(list<String> Fleetids,String action){
        system.debug('***'+fleetids+'***'+action);
        AggregateResult[] groupedResults = [SELECT COUNT(Id), Unit__c FROM SBQQ__QuoteLine__c  
                                            where Unit__c IN :Fleetids and Contract_Expired__c = false GROUP BY Unit__c ];
        system.debug('***'+groupedResults);
        list<Fleet__c> FleetList = new list<Fleet__c>();
        for(AggregateResult a:groupedResults) {     
            Id BId = (ID)a.get('Unit__c');  
            Integer count;
            if(action == 'Delete'){
              system.debug('***Setting Count to 0 on Delete Action***');
              count = 0;  
            }
            else{   
                system.debug('***Setting Count to 1 on Update/Insert Action***');
                count = 1;
            }
            if(BId!= null){
				Fleet__c objB = new Fleet__c(); 
            	objB.id=BId;
            	objB.CountUsed__c  = count;
            	system.debug('***objB***'+objB);			
           
            	FleetList.add(objB); 
			 }
        } 
        if(!FleetList.isEmpty()){
            update FleetList;
        }
    }
    
    public static void getFleetCountOld(list<String> Fleetids,String action){
        system.debug('***'+fleetids+'***'+action);
        AggregateResult[] groupedResults = [SELECT Id FROM Fleet__c  
                                            where Id IN :Fleetids GROUP BY Id];
        system.debug('***'+groupedResults);
        list<Fleet__c> FleetList = new list<Fleet__c>();
        for(AggregateResult a:groupedResults) {     
            Id BId = (ID)a.get('Id');  
            Integer count;
              system.debug('***Setting Count to 0 on removing old unit from the QL***');
              count = 0;  
            if(BId!= null){
				Fleet__c objB = new Fleet__c(); 
            	objB.id=BId;
            	objB.CountUsed__c  = count;
            	system.debug('***objB***'+objB);			
           
            	FleetList.add(objB); 
			 }
        } 
        if(!FleetList.isEmpty()){
            update FleetList;
        }
    }
}