unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/NS_Linked_Rental_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Linked_Rental_Item_ID__c</fullName>
    <label>NS Linked Rental Item ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/NS_Rental_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Rental_Item_ID__c</fullName>
    <label>NS Rental Item ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line's product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup of the fleet item corresponding to this product/quote line item</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2)</booleanFilter>
        <filterItems>
            <field>Fleet__c.Rental_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Fleet__c.WIP_Asset__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/QuoteLineLinkedRentalItemHandler.cls
public class QuoteLineLinkedRentalItemHandler {

    public static void run(List<SBQQ__QuoteLine__c> newList) {
        if (newList == null || newList.isEmpty()) return;

        // Map Trigger.new by Id so we can set fields on the live instances
        Map<Id, SBQQ__QuoteLine__c> liveById = new Map<Id, SBQQ__QuoteLine__c>();
        Set<Id> newIds = new Set<Id>();
        for (SBQQ__QuoteLine__c ql : newList) {
            if (ql.Id != null) {
                newIds.add(ql.Id);
                liveById.put(ql.Id, ql);
            }
        }
        if (newIds.isEmpty()) return;

        // Pull only the lines in context that are Insurance / Personal Property Fee
        Map<Id, SBQQ__QuoteLine__c> feeLinesEnrichedById = new Map<Id, SBQQ__QuoteLine__c>(
            [
                SELECT Id,
                       SBQQ__RequiredBy__c,
                       SBQQ__Product__r.Name
                FROM SBQQ__QuoteLine__c
                WHERE Id IN :newIds
                  AND SBQQ__Product__r.Name IN ('Insurance', 'Personal Property Fee')
            ]
        );
        if (feeLinesEnrichedById.isEmpty()) return;

        // Collect their RequiredBy parents
        Set<Id> parentReqByIds = new Set<Id>();
        for (SBQQ__QuoteLine__c feeRow : feeLinesEnrichedById.values()) {
            if (feeRow.SBQQ__RequiredBy__c != null) {
                parentReqByIds.add(feeRow.SBQQ__RequiredBy__c);
            }
        }
        if (parentReqByIds.isEmpty()) return;

        // Pull all siblings that share those RequiredBy parents
        // "First" is determined by CreatedDate ASC
        List<SBQQ__QuoteLine__c> siblings = [
            SELECT Id,
                   SBQQ__RequiredBy__c,
                   Unit__c,
                   NS_Rental_Item_ID__c,
                   CreatedDate
            FROM SBQQ__QuoteLine__c
            WHERE SBQQ__RequiredBy__c IN :parentReqByIds
            ORDER BY CreatedDate ASC
        ];

        // For each parent, store the first sibling that has Unit__c and NS_Rental_Item_ID__c
        Map<Id, String> firstRentalIdByParent = new Map<Id, String>();
        for (SBQQ__QuoteLine__c s : siblings) {
            // Only set once per parent (the first one in CreatedDate order)
            if (!firstRentalIdByParent.containsKey(s.SBQQ__RequiredBy__c)) {
                Boolean hasUnit = (s.Unit__c != null && String.isNotBlank(String.valueOf(s.Unit__c)));
               Boolean hasRental = (s.Id != null && String.isNotBlank(s.Id));
                if (hasUnit && hasRental) {
                    firstRentalIdByParent.put(s.SBQQ__RequiredBy__c, s.Id);
                }
            }
        }

        // Set NS_Linked_Rental_Item_ID__c on the live fee lines
        for (Id feeId : feeLinesEnrichedById.keySet()) {
            SBQQ__QuoteLine__c feeEnriched = feeLinesEnrichedById.get(feeId);
            SBQQ__QuoteLine__c feeLive = liveById.get(feeId);
            if (feeEnriched == null || feeLive == null) continue;

            Id parentId = feeEnriched.SBQQ__RequiredBy__c;
            if (parentId == null) continue;

            String rentalId = firstRentalIdByParent.get(parentId);
            if (rentalId != null) {
                feeLive.NS_Linked_Rental_Item_ID__c = rentalId;
            }
            // else: leave as-is (no clearing)
        }
    }
}