unpackaged/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Contract_Expired__c.field-meta.xml
<CustomField>
    <fullName>Contract_Expired__c</fullName>
    <formula>IF( Contract_End_Date__c &lt; Today(),TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Expired</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Primary_Quote__c.field-meta.xml
<CustomField>
    <fullName>Primary_Quote__c</fullName>
    <formula>SBQQ__Quote__r.SBQQ__Primary__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Quote</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Renewal_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Quote_Line__c</fullName>
    <formula>SBQQ__Quote__r.SBQQ__Opportunity2__r.Renewal_Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Quote Line</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup of the fleet item corresponding to this product/quote line item</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2)</booleanFilter>
        <filterItems>
            <field>Fleet__c.Rental_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Fleet__c.WIP_Asset__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FleetCountTriggerHandlerTest.cls
@isTest(seealldata = true)
public class FleetCountTriggerHandlerTest {
    @isTest
    public static void testMethod1(){
      list<SBQQ__QuoteLine__c> lstquote =  [select Id,Contract_Expired__c,Unit__c,Primary_Quote__c, Renewal_Quote_Line__c from SBQQ__QuoteLine__c where Renewal_Quote_Line__c = true AND Contract_Expired__c = false AND Primary_Quote__c = true  limit 1];
        if(!lstquote.isEmpty()){
            SBQQ__QuoteLine__c SS = new SBQQ__QuoteLine__c();
            SS.Id = lstquote[0].Id;
           SS.Unit__c = 'a0CI90000005xTkMAI';
            update SS;
            
		} 
    }
	@isTest
    public static void testMethod2(){
      list<SBQQ__QuoteLine__c> lstquote =  [select Id,Name,Contract_Expired__c,Unit__c,Primary_Quote__c, Renewal_Quote_Line__c from SBQQ__QuoteLine__c where Renewal_Quote_Line__c = true AND Contract_Expired__c = false AND Primary_Quote__c = true  limit 1];
        string QName;
       if(!lstquote.isEmpty()){
           QName = lstquote[0].Name;
            delete lstquote;
		}
        list<SBQQ__QuoteLine__c> lstdel = [select Id from SBQQ__QuoteLine__c where Name =:QName ALL ROWS ];
        undelete lstdel;
    }
    
}